# Generated by Django 5.1.4 on 2025-04-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_article_content_article_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('tech', 'Технологии'), ('science', 'Наука'), ('health', 'Здоровье'), ('education', 'Образование')], default='tech', max_length=20, verbose_name='Категория'),
        ),
    ]
